#!/bin/bash
pkg_name=${@: -1}

SCRIPT=$(readlink -f "$0")
BASEDIR=$(dirname "$SCRIPT")
export PKG_CONFIG_PATH=${BASEDIR}/toolchain-android/lib/pkgconfig
case $1 in
  --exists)
    pkg-config --exists $pkg_name
    ;;
  --cflags)
    echo $(pkg-config --cflags $pkg_name)
    ;;
  --libs)
    if [ $2 = "sdl" ]; then
        echo "$(pkg-config --libs $pkg_name) -Wl,--unresolved-symbols,ignore-in-object-files"
        exit 0
    fi
    echo $(pkg-config --libs $pkg_name)
    ;;
  *)
    echo "FFmpeg pkg-config to build FFmpeg for Android!"
    ;;
esac
